export enum COURSES_ENUM {
    INFORMATICA = "Informatica",
    MEDICINA = "Medicina",
    LINGUE = "Lingue e Culture Straniere",
}

export enum NOTIFICATION_TYPE {
    FRIEND_REQUEST = "FRIEND_REQUEST",
    FRIEND_REQUEST_ACCEPTED = "FRIEND_REQUEST_ACCEPTED",
    FRIEND_REQUEST_REFUSED = "FRIEND_REQUEST_REFUSED",
    SUGGEST_FRIEND = "SUGGEST_FRIEND",
    SUGGEST_TOPIC = "SUGGEST_TOPIC",
    SUGGEST_EVENT = "SUGGEST_EVENT",
    SHARE_TOPIC = "SHARE_TOPIC",
    SHARE_EVENT = "SHARE_EVENT",
    TAG_COMMENT = "TAG_COMMENT",
    TAG_TOPIC = "TAG_TOPIC",
    TAG_EVENT= "TAG_EVENT",
    COMMENT_REPLY="COMMENT_REPLY",
    COMMENT_LIKE="COMMENT_LIKE",
    COMMENT_DISLIKE="COMMENT_DISLIKE",
    COMMENT_NEW_TOPIC="COMMENT_NEW_TOPIC",
    COMMENT_NEW_EVENT="COMMENT_NEW_EVENT",
    UPDATE_TERMS="UPDATE_TERMS",
    TICKET_SYSTEM_REPLY="TICKET_SYSTEM_REPLY",
    TICKET_SEAT_ASSIGNED="TICKET_SEAT_ASSIGNED",
    PAYMENT_REFUSED="PAYMENT_REFUSED"
}