# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - unievent2024

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_088a1cc862ef484a8836d33510f38a4a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3e425dd527c0440592946259a934800a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        username: ${{ secrets.AzureAppService_ContainerUsername_088a1cc862ef484a8836d33510f38a4a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3e425dd527c0440592946259a934800a }}
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_088a1cc862ef484a8836d33510f38a4a }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'unievent2024'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e6b7769563b84512a8124d904b65c1cc }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_088a1cc862ef484a8836d33510f38a4a }}/appsvc/staticsite:${{ github.sha }}'
